/* eslint-disable no-var */
/**
 * @see https://developer.ones.cn/docs/guide/advanced/storage
 * @summary ones.d.ts is generated by `op format` cli commands.
 * DO NOT MODIFY MANUALLY
 */
declare var ONESEntities: {
    sso_state: {
        attributes: {
            value?: string;
            updated_at?: string;
        };
        indexes: null;
    };
    sync_audit: {
        attributes: {
            pulled_at?: string;
            dept_count?: number;
            user_count?: number;
            skipped_count?: number;
            error?: string;
        };
        indexes: null;
    };
};
